"""tables

Revision ID: ddb691ac423b
Revises: d7f2444d153a
Create Date: 2022-05-06 22:01:20.399098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb691ac423b'
down_revision = 'd7f2444d153a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_timestamp'), 'meals', ['timestamp'], unique=False)
    op.create_table('top_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ganush', sa.String(length=64), nullable=True),
    sa.Column('gijooo', sa.String(length=65), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_model_ganush'), 'top_model', ['ganush'], unique=True)
    op.create_index(op.f('ix_top_model_timestamp'), 'top_model', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_model_timestamp'), table_name='top_model')
    op.drop_index(op.f('ix_top_model_ganush'), table_name='top_model')
    op.drop_table('top_model')
    op.drop_index(op.f('ix_meals_timestamp'), table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###
